before_script:
DATABASE_URL = "postgres://zfjkjgkf:Z29yHoUDKXlKOXCn6-IzLsu_MgdUKq0V@salt.db.elephantsql.com:5432/zfjkjgkf"
language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
    after_success:
  - npm run coverage
  script: "npm run test"